fastlane_version "2.112.0"

default_platform :ios

UPDATE_USAGE = "usage: fastlane deploy bump_type:[major|minor|patch]"

platform :ios do

  desc UPDATE_USAGE
  lane :update_version_number do |options|
	x_version = sh("grep -r X.X.X ../CHANGELOG.md | wc -l | tr -d ' \n\r'")
	if x_version != "1"
		UI.user_error!("Be sure to have only one intermediate version: [X.X.X] present in CHANGELOG file")
	end

	if ["major", "minor", "patch"].include?(options[:bump_type])
		version = version_bump_podspec(bump_type: options[:bump_type])
		increment_version_number(version_number: "#{version}")
		sh("sed -i '' 's/X.X.X/#{version}/g' ../CHANGELOG.md")
		cocoapods
	else
		UI.user_error!(UPDATE_USAGE)
	end
  end
end
